### ISSUE TITLE
关于代码优化

### ISSUE THREAD

**Issue by aJacke** [aJacke/pcr_wiki_bydb#1]
因为我个人秉持的先尽快搓出一个能用的代码的原则，先搓出来的成品可能效率堪忧，虽说对于正常使用来说影响不大，但我大概率会考虑在完成之后进行小幅度的优化代码吧

**Comment by duoshoumiao** [comment]
非常期待

**Comment by duoshoumiao** [comment]
好像国服没实装的会报错
[2025-01-04 15:28:54,869 nonebot] INFO: Self: 1591635791, Message 1910090155 from 645364231@[群:428682530]: '琳德技能'
[2025-01-04 15:28:54,869] INFO in message: Self: 1591635791, Message 1910090155 from 645364231@[群:428682530]: '琳德技能'
[2025-01-04 15:28:54,869 pcr_wiki_bydb] INFO: Message 1910090155 triggered chara_intro.
[2025-01-04 15:28:54,869] INFO in msghandler: Message 1910090155 triggered chara_intro.
[2025-01-04 15:28:55,002 pcr_wiki_bydb] ERROR: <class 'TypeError'> occured when chara_intro handling message 1910090155.
[2025-01-04 15:28:55,002] ERROR in msghandler: <class 'TypeError'> occured when chara_intro handling message 1910090155.
[2025-01-04 15:28:55,017 pcr_wiki_bydb] ERROR: cannot unpack non-iterable int object
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\8090\HoshinoBot-master\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\8090\HoshinoBot-master\hoshino\modules\pcr_wiki_bydb\main.py", line 77, in chara_intro
    uid, c = await get_chara_uid(name, bot, ev)
TypeError: cannot unpack non-iterable int object
[2025-01-04 15:28:55,017] ERROR in msghandler: cannot unpack non-iterable int object
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\8090\HoshinoBot-master\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\8090\HoshinoBot-master\hoshino\modules\pcr_wiki_bydb\main.py", line 77, in chara_intro
    uid, c = await get_chara_uid(name, bot, ev)
TypeError: cannot unpack non-iterable int object

**Comment by aJacke** [comment]
其实没有完全写完，但是理论上会拾取大部分可能的报错作为回复消息，你的数据库是最新的吗（仓库的很久没更新了）

**Comment by aJacke** [comment]
然后关于bug最好还是单独开一个issue比较好，这边很难做有效统计的

**Comment by duoshoumiao** [comment]
刚拉取的db

**Comment by duoshoumiao** [comment]
> 然后关于bug最好还是单独开一个问题比较好，很难做有效统计的

好，到时候我再来拉取

**Comment by aJacke** [comment]
> > 然后关于bug最好还是单独开一个问题比较好，很难做有效统计的
> 
> 好，到时候我再来拉取

我这边复现不了你说的bug，你能单开一个做反馈吗
